on: pull_request
jobs:
  tests:
    runs-on: rust
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
      - uses: actions/cache@v3
        with:
          path: |
            ~/target
